ignore coredumps, adds exit status propagation through lime-run

diff --git a/tools/devcontainer/lime-run b/tools/devcontainer/lime-run
--- a/tools/devcontainer/lime-run
+++ b/tools/devcontainer/lime-run
@@ -50,12 +50,15 @@ if [[ -x "$LIME_DIR"/lime ]]; then
     if [[ $# -eq 0 ]]; then
         cd "$DEFAULT_MODEL" || exit
         bash "$LIME_DIR"/lime -n ./model.c
+        LIME_EXIT_STATUS=$?
     else
         bash "$LIME_DIR"/lime "$@"
+        LIME_EXIT_STATUS=$?
     fi
     cleanup
+    exit $LIME_EXIT_STATUS
 else
-    echo "lime excutable (${LIME}) not found."
+    echo "lime executable (${LIME}) not found."
     exit 3
 fi
 
